### ISSUE TITLE
CSV Files Missing

### ISSUE THREAD

**Issue by nimitbindal** [yogeshg/Twitter-Sentiment#1]
sentiment.py needs sentiment.csv, which is not present in the repo. Am I missing something?

**Comment by yogeshg** [comment]
No you aren't. I'll send datasets separately. Didn't put them in the repo
cuz size.

**Comment by nimitbindal** [comment]
Ok. Thanks.

And regarding the report, it describes most of the things clearly. There were few spelling mistakes and figure and bibliography reference errors, which you might have corrected by now.
Since I don't yet know the stuff too deeply, I can't comment on theoretical correctness.
On the presentation side of the report, I would suggest you to use better tools to make graphs.

Best,
Nimit

Sent from my Sony Xperia™ smartphone

---- Yogesh Garg wrote ----

> No you aren't. I'll send datasets separately. Didn't put them in the repo 
> cuz size.

**Comment by yogeshg** [comment]
Thanks. Please tell me the mistakes, I haven;t really corrected anything.
Actually, you can give very relevant opinion precisely because you just
started working on it. How do you feel about the language used? Is there
anything that required more explanation? What can else can I cover in my
report?

Thanks.

_Yogesh Garg_

**Comment by imnimn** [comment]
Can you please send me the sentiment.csv file ?
Thanks,

**Comment by yogeshg** [comment]
As mentioned in the Readme, I used the following link for downloading data:
http://www.sananalytics.com/lab/twitter-sentiment/
Please go through the steps as suggested in the website.

**Comment by imnimn** [comment]
Thank you very much Mr. Yogesh Garg

**Comment by raghavkishan** [comment]
Hello yogeshg,

Need your help. 
Even after going through comments ad read me file, I am unable to find the 'sentiment.csv' file. Please let me know how to proceed on this.

Thanks

**Comment by yogeshg** [comment]
As mentioned in the Readme, I used the following link for downloading data:
http://www.sananalytics.com/lab/twitter-sentiment/
Please go through the steps as suggested in the website.

*Yogesh Garg*

**Comment by yogeshg** [comment]
Were you able to generate the  sentiment.csv file?

*Yogesh Garg*

**Comment by raghavkishan** [comment]
No. I haven't been able to do it. Please let me know what should be the content of the csv?

**Comment by c1260415** [comment]
Hello yogeshg,

I already had stanfordcorpus , they have two files 1.testdata.manual.2009.06.14.csv 2.training.1600000.processed.noemoticon.csv

but when I run sentiment.py I got error "IOError: [Errno 2] No such file or directory: 'stanfordcorpus/training.1600000.processed.noemoticon.csv.5000.norm.csv'"

I cant find the file in stanfordcorpus 

Need Help

Thank you

**Comment by imnimn** [comment]
Well 
I have tried that too,
I have downloaded the code in the website you wrote, 
but, I guess that, the tweets, for the saved IDs, are no longer in the server.
So no tweets appeared, and the code didn't work

**Comment by leoking90** [comment]
Hi, Is this possible for you to send me sentiment.csv file? My email address is: 'm.umar090@gmail.com' Thank You

**Comment by somiyaa** [comment]
will you be able to send me sentiment.csv file ?

**Comment by LakshmiPrasath** [comment]
Hi Yogesh, 
It was really interesting paper and source code. I am writing a thesis on opinion mining and going to cite your paper with your permission. But still I am not able to find the sentiment.csv and stanfordcorpus/training.1600000.processed.noemoticon.csv.5000.norm.csv' to see your results.

Can you please send those files to my mail id : lakshmiprasath.m@gmail.com

Regards,
Lak

**Comment by nimitbindal** [comment]
Hi,

https://drive.google.com/open?id=0B1qqMD7ptIfcUjJBUTUwN25sSW8

Link to the data sets.

-Nimit Bindal

**Comment by yogeshg** [comment]
Thank you very much, @nimitbindal ; this makes it easier for many people to use the repo!
@LakshmiPrasath , please feel free to cite the paper.
If you run into more problems while running this, I can try to fix it with the data now available.
